### ISSUE TITLE
Error: Failed to lookup view "signup" in views directory "E:\MyProject\shop\views\pages"

### ISSUE THREAD

**Issue by mlyknown** [njaulj/Bigyima.shop#2]
Error: Failed to lookup view "signup" in views directory "E:\MyProject\shop\views\pages"
还有个views文件夹啊

**Comment by njaulj** [comment]
界面因为是用的别人的模块，避免侵权，我给删掉了

**Comment by mlyknown** [comment]
可以邮件一份吗？感觉做的挺全的，想研究法 0.0

**Comment by njaulj** [comment]
代码早就删掉了啊，不好意思
